version: '3.1'

services:
  # mongodb installation (it generates the "data" subdir in the project)
  mongodb:
    image: mongo:5.0.8
    restart: on-failure
    volumes:
     - ./data/db:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      default:
        ipv4_address: 172.19.0.7

  # development only dashboard for easily checking db changes
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongodb:27017/"
    depends_on:
      - mongodb
    networks:
      default:
        ipv4_address: 172.19.0.3

  # FastAPI backend (served by uvicorn in development)
  server:
    build:
      context: ./server
      dockerfile: docker/FastAPI/Dockerfile
    volumes:
      - ./server/src:/src
      - ./server/test_data_base:/test_data_base
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - testidp
    links:
      - testidp
    networks:
      default:
        ipv4_address: 172.19.0.6

  # web server (acting as a reverse proxy in production)
  nginx:
    build: ./server/docker/nginx
    volumes:
      - ./server/static:/static
    ports:
      - "80:80"
    depends_on:
      - server
    restart: on-failure
    networks:
      default:
        ipv4_address: 172.19.0.4

  # ReactJS frontend (run with npm start in development)
  client:
    build:
      context: ./client
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./client/public:/app/public
      - ./client/src:/app/src
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    networks:
      default:
        ipv4_address: 172.19.0.5

  # Test IdP as a replacement for Shibboleth.
  # TODO: DELETE IN PRODUCTION!
  testidp:
    image: quay.io/keycloak/keycloak:20.0.1
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    volumes:
      - ./keycloak/data/:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    command:
      - start-dev --import-realm
    networks:
      default:
        ipv4_address: 172.19.0.2

  # A way to test the authentication flow without the need of public IP addresses.
  # TODO: DELETE IN PRODUCTION!
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./firefox:/config
    ports:
      - "5800:3000"
    shm_size: "1gb"
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.19.0.8

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1