# Use root/example as user/password credentials
version: '3.1'

services:
  # mongodb installation (it generates the "data" subdir in the project)
  mongodb:
    image: mongo
    restart: on-failure
    volumes:
     - ./data/db:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # development only dashboard for easily checking db changes
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongodb

  # FastAPI backend (served by uvicorn in development)
  server:
    build:
      context: server
      dockerfile: ./docker/fastAPI/Dockerfile
    volumes:
      - ./server/fastAPI:/code
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  # web server (acting as a reverse proxy in production)
  nginx:
    build: ./server/docker/nginx
    volumes:
      - ./server/static:/static
    ports:
      - "80:80"
    depends_on:
      - server
    restart: on-failure

  # ReactJS frontend (run with npm start in development)
  client:
    build:
      context: ./client
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./client:/app
    command: ["npm", "start"]
    ports:
      - "3000:3000"