name: Lint

on:
  push:
    branches:
      - master

jobs:
  run-client-linters:
    name: Run Client Linters
    runs-on: ubuntu-latest
    if: ${{ github.event.pusher.name != 'weee-open-bot' }}
    defaults:
      run:
        working-directory: .

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_ACTIONS_BOT_PAT }}

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17

      - name: Set up git credentials
        run: |
          git config --global user.email "weee-open-bot@users.noreply.github.com"
          git config --global user.name "weee-open-bot"

      - name: Run ESLint
        run: npx --no-install eslint --ext .js --ext .jsx --fix --no-color --format json  "./client"
        continue-on-error: true

      - name: Commit ESLint changes
        run: |
          git commit -am "Fix code style issues with ESLint" || echo "No changes to commit"

      - name: Run Prettier
        run: npx --no-install prettier --write "./client"
        continue-on-error: true

      - name: Commit Prettier changes
        run: |
          git commit -am "Fix code style issues with Prettier" || echo "No changes to commit"

      - name: Push changes
        run: git push

  run-server-linters:
    name: Run Server Linters
    runs-on: ubuntu-latest
    if: ${{ github.event.pusher.name != 'weee-open-bot' }}
    needs:
      - run-client-linters
    defaults:
      run:
        working-directory: server

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_ACTIONS_BOT_PAT }}

      - name: Set up git credentials
        run: |
          git config --global user.email "weee-open-bot@users.noreply.github.com"
          git config --global user.name "weee-open-bot"

      - name: Pull changes made by other CI jobs
        run: git pull

      - name: Push changes
        run: git push

  run-ml-linters:
    name: Run ML Linters
    runs-on: ubuntu-latest
    if: ${{ github.event.pusher.name != 'weee-open-bot' }}
    needs:
      - run-server-linters
    defaults:
      run:
        working-directory: ml

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_ACTIONS_BOT_PAT }}

      - name: Set up git credentials
        run: |
          git config --global user.email "weee-open-bot@users.noreply.github.com"
          git config --global user.name "weee-open-bot"

      - name: Pull changes made by other CI jobs
        run: git pull

      - name: Push changes
        run: git push